version: "3"
services:
  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "80"
    volumes:
      - ./server:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
