services:
  client:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app 
      - /app/node_modules
    depends_on:
      - server      
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped