name: Client CI

on:
  push:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './client/package.json'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: Run linting
      run: npm run lint --if-present
