name: Server CI

on:
  push:
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: './server/package.json'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: Run tests
      run: npm test --if-present
      
    - name: Run linting
      run: npm run lint --if-present
